version: '3'
services:
  flask: # Docker-Dienst f端r Flask-Anwendung
    build:
      context: .
      dockerfile: Dockerfile_Flask
    image: athika98/sbbproject:flask  # Das Image nur f端r den Flask-Dienst
    ports:
      - "5001:5001"
    restart: always

  svelte: # Docker-Dienst f端r Svelte-Anwendung
    build:
      context: .
      dockerfile: Dockerfile_Svelte
    image: athika98/sbbproject:svelte  # Das Image nur f端r den Svelte-Dienst
    ports:
      - "4173:4173"
    restart: always