# Usage: docker-compose build
# docker login mit user und token

FROM python:3.12.1 AS backend

# Setze das Arbeitsverzeichnis im Container 
WORKDIR /usr/src/app/backend

# Erforderliche Dateien kopieren
COPY backend/ .

# Abhängigkeiten installieren
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# EXPO
EXPOSE 5001
ENV FLASK_APP=/usr/src/app/backend/backend.py

# Anwendung starten
CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0", "--port=5001"]