version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile_Flask
    image: athika98/sbbproject:flask  # Das Image für den Flask-Dienst
    ports:
      - "5001:5001"
    restart: always

  svelte:
    build:
      context: .
      dockerfile: Dockerfile_Svelte
    image: athika98/sbbproject:svelte  # Das Image für den Svelte-Dienst
    ports:
      - "4173:4173"
    restart: always