name: SBB Project Automation Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  data_processing_and_model_training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'
          cache: 'pip'

      - name: Install Python Packages
        run: pip install -r requirements.txt

      - name: Fetch SBB Data
        run: python ./getsbbdata.py
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}

      - name: Upload BFS Data
        run: python ./uploadbfsdata.py
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}

      - name: Train Model
        run: python ./model.py
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}

      - name: Upload Model to Azure Blob Storage
        run: python ./save.py -c "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" -f modelHA.pkl modelGA.pkl
